apiVersion: v1
kind: Namespace
metadata:
  name: c2c-hpe-matt-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-hpe-matt-deployment
  namespace: c2c-hpe-matt-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:060d837a167ccd17a85d00f470553790d607e9be

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-hpe-matt-label
  name: c2c-hpe-matt-service
  namespace: c2c-hpe-matt-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---